module.exports = [
                    {
                        groupTitle: 'CFT 총괄',
                        members: [
                            {
                                name: '이철승',
                                photo: '이철승',
                                roles: ['리얼에셋부문/부문대표', '사업&개발/부문대표', '기업마케팅센터/부문대표', 'IOTA CFT/TF장', 'SMP/SMP'],
                                responsibility: 'CFT 총괄 책임인력',
                                email: 'ethan.lee@igisam.com',
                                phone: '010-3186-0868',
                            },
                            {
                                name: '윤관식',
                                photo: '윤관식',
                                roles: ['투자&펀딩/부대표', '투자1그룹/부대표', '투자1그룹4파트/부대표', '양재TF/TF장'],
                                responsibility: 'CFT 총괄(Sub PO)',
                                email: 'gwansik.yoon@igisam.com',
                                phone: '010-7368-0309',
                            },
                            {
                                name: '정조민',
                                photo: '정조민',
                                roles: ['관리&운영/부대표', '리빙그룹/부대표', '전략펀드운용3실', '전략펀드운용1실', '전략펀드운용2실', '리테일솔루션센터/부대표'],
                                responsibility: 'CFT 총괄(Sub PO)',
                                email: 'jmjung@igisam.com',
                                phone: '010-6341-0174',
                            },
                            {
                                name: '우형석',
                                photo: '우형석',
                                roles: ['사업그룹/그룹장', '전략펀드운용1실', '사업그룹3파트/그룹장'],
                                responsibility: 'CFT 총괄(Sub PO)',
                                email: 'hyungsuk.woo@igisam.com',
                                phone: '010-8893-7572',
                            },
                        ]
                    },
                    {
                        groupTitle: '사업PM',
                        members: [
                            {
                                name: '권순일',
                                photo: '권순일',
                                roles: ['사업그룹1파트/파트장+', 'IOTA CFT', '개발PFV TF/TF장'],
                                responsibility: '사업PM · IPR · 전략자문\n책임인력',
                                email: 'ksoonil@igisam.com',
                                phone: '010-8567-6907',
                            },
                            {
                                name: '강순용',
                                photo: '강순용',
                                roles: ['사업그룹2파트/파트장+', 'IOTA CFT'],
                                responsibility: '사업PM 책임인력',
                                email: 'sykang@igisam.com',
                                phone: '010-8274-4638',
                            },
                            {
                                name: '윤주형',
                                photo: '윤주형',
                                roles: ['사업그룹1파트/Sr.Manager', 'IOTA CFT'],
                                email: 'jh.yoon@igisam.com',
                                phone: '010-5210-1418',
                            },
                            {
                                name: '김제익',
                                photo: '김제익',
                                roles: ['사업그룹1파트', 'IOTA CFT'],
                                email: 'jake.kim@igisam.com',
                                phone: '010-5055-8197',
                            },
                            {
                                name: '류홍',
                                photo: '류홍',
                                roles: ['사업그룹1파트', 'IOTA CFT'],
                                email: 'ryuhong0526@igisam.com',
                                phone: '010-9081-7818',
                            },
                            {
                                name: '박만진',
                                photo: '박만진',
                                roles: ['사업그룹1파트', 'IOTA CFT'],
                                email: 'jacob.park@igisam.com',
                                phone: '010-4343-7438',
                            },
                            {
                                name: '박일훈',
                                photo: '박일훈',
                                roles: ['사업그룹1파트', 'IOTA CFT'],
                                email: 'ilhoon.park@igisam.com',
                                phone: '010-7573-6985',
                            },
                            {
                                name: '이정원',
                                photo: '이정원',
                                roles: ['사업그룹1파트+', 'IOTA CFT'],
                                email: 'garden.lee@igisam.com',
                                phone: '010-3161-2931',
                            },
                            {
                                name: '전무경',
                                photo: '전무경',
                                roles: ['사업그룹1파트', 'IOTA CFT'],
                                email: 'mooj@igisam.com',
                                phone: '010-2464-3709',
                            },
                            {
                                name: '한찬호',
                                photo: '한찬호',
                                roles: ['사업그룹2파트/Sr.Manager+', 'IOTA CFT'],
                                email: 'chanho.han@igisam.com',
                                phone: '010-4818-2108',
                            },
                            {
                                name: '박석제',
                                photo: '박석제',
                                roles: ['사업그룹2파트', 'IOTA CFT'],
                                email: 'seokje.park@igisam.com',
                                phone: '010-3319-9395',
                            },
                            {
                                name: '박채현',
                                photo: '박채현',
                                roles: ['사업그룹2파트', 'IOTA CFT'],
                                email: 'p.chhyn@igisam.com',
                                phone: '010-5095-1915',
                            },
                            {
                                name: '소현준',
                                photo: '소현준',
                                roles: ['사업그룹2파트', 'IOTA CFT'],
                                email: 'hyunjoon.so@igisam.com',
                                phone: '010-3857-6793',
                            },
                            {
                                name: '이수정',
                                photo: '이수정',
                                roles: ['사업그룹2파트', 'IOTA CFT'],
                                email: 'sjl1747@igisam.com',
                                phone: '010-9222-1747',
                            },
                            {
                                name: '조영비',
                                photo: '조영비',
                                roles: ['사업그룹2파트', 'IOTA CFT'],
                                email: 'youngbi@igisam.com',
                                phone: '010-2059-6511',
                            },
                            {
                                name: '한수정',
                                photo: '한수정',
                                roles: ['사업그룹2파트', 'IOTA CFT'],
                                email: 'soojeong.han@igisam.com',
                                phone: '010-7609-5868',
                            },
                        ]
                    },
                    {
                        groupTitle: '파이낸싱',
                        members: [
                            {
                                name: '박준호',
                                photo: '박준호',
                                roles: ['Loan Finance센터/센터장+'],
                                responsibility: '파이낸싱 책임인력',
                                email: 'junhopark@igisam.com',
                                phone: '010-9230-5400',
                            },
                            {
                                name: '강석민',
                                photo: '강석민',
                                roles: ['Loan Finance센터/Sr.Manager'],
                                email: 'sm.kang@igisam.com',
                                phone: '010-9091-1055',
                            },
                            {
                                name: '정리훈',
                                photo: '정리훈',
                                roles: ['Loan Finance센터/Sr.Manager'],
                                email: 'jlh@igisam.com',
                                phone: '010-2983-1503',
                            },
                            {
                                name: '손유정',
                                photo: '손유정',
                                roles: ['Loan Finance센터'],
                                email: 'yujung.son@igisam.com',
                                phone: '010-2863-3892',
                            },
                            {
                                name: '김지우',
                                photo: '김지우',
                                roles: ['Loan Finance센터'],
                                email: 'jiwoo@igisam.com',
                                phone: '010-5541-5394',
                            },
                            {
                                name: '박현승',
                                photo: '박현승',
                                roles: ['Loan Finance센터'],
                                email: 'hyunpark@igisam.com',
                                phone: '010-5376-8842',
                            },
                            {
                                name: '이성민A',
                                photo: '이성민A',
                                roles: ['Loan Finance센터'],
                                email: 'stealth@igisam.com',
                                phone: '010-3074-3396',
                            },
                            {
                                name: '한승환',
                                photo: '한승환',
                                roles: ['Loan Finance센터'],
                                email: 'seunghwanhan@igisam.com',
                                phone: '010-2722-9946',
                            },
                        ]
                    },
                    {
                        groupTitle: '개발관리',
                        members: [
                            {
                                name: '홍장군',
                                photo: '홍장군',
                                roles: ['개발솔루션센터/센터장+'],
                                responsibility: '개발관리 책임인력',
                                email: 'jghong@igisam.com',
                                phone: '010-6229-8919',
                            },
                            {
                                name: '채원',
                                photo: '채원',
                                roles: ['개발솔루션센터/담당+'],
                                email: 'won.chae@igisam.com',
                                phone: '010-7222-7469',
                            },
                            {
                                name: '김보성',
                                photo: '김보성',
                                roles: ['개발솔루션센터'],
                                email: 'kbs1208@igisam.com',
                                phone: '010-2369-2069',
                            },
                            {
                                name: '전승희',
                                photo: '전승희',
                                roles: ['개발솔루션센터'],
                                email: 'shjeon@igisam.com',
                                phone: '010-3804-6529',
                            },
                            {
                                name: '김대익',
                                photo: '김대익',
                                roles: ['개발솔루션센터'],
                                email: 'dikim@igisam.com',
                                phone: '010-9251-3466',
                            },
                            {
                                name: '장성진',
                                photo: '장성진',
                                roles: ['개발솔루션센터'],
                                email: 'jang.sj@igisam.com',
                                phone: '010-9680-3293',
                            },
                            {
                                name: '이정훈',
                                photo: '이정훈',
                                roles: ['개발솔루션센터/담당'],
                                email: '2019jhlee@igisam.com',
                                phone: '010-4175-5799',
                            },
                            {
                                name: '박봉서',
                                photo: '박봉서',
                                roles: ['개발솔루션센터/담당'],
                                email: 'okbong21@igisam.com',
                                phone: '010-3370-3594',
                            },
                        ]
                    },
                    {
                        groupTitle: '기업마케팅',
                        members: [
                            {
                                name: '김민지',
                                photo: '김민지',
                                roles: ['기업마케팅센터/Sr.Manager'],
                                responsibility: '기업마케팅 책임인력',
                                email: 'minjik@igisam.com',
                                phone: '010-5454-5322',
                            },
                            {
                                name: '고아라',
                                photo: '고아라',
                                roles: ['기업마케팅센터'],
                                email: 'argoh@igisam.com',
                                phone: '010-4701-7725',
                            },
                            {
                                name: '이가현',
                                photo: '이가현',
                                roles: ['공간솔루션센터/리더'],
                                email: 'ghlee@igisam.com',
                                phone: '010-7114-5070',
                            },
                            {
                                name: '정수명',
                                photo: '정수명',
                                roles: ['공간솔루션센터'],
                                email: 'smchung@igisam.com',
                                phone: '010-5011-9459',
                            },
                        ]
                    },
                    {
                        groupTitle: '상품·디지털',
                        members: [
                            {
                                name: '김현수',
                                photo: '김현수',
                                roles: ['공간솔루션센터/센터장+'],
                                responsibility: '상품·디지털 책임인력',
                                email: 'hyunsoo.kim@igisam.com',
                                phone: '010-2078-2999',
                            },
                            {
                                name: '현철호',
                                photo: '현철호',
                                roles: ['디지털사업그룹/그룹장', '솔루션파트/그룹장', 'IOTA CFT'],
                                responsibility: '상품·디지털 책임인력',
                                email: 'chyun@igisam.com',
                                phone: '010-3368-1331',
                            },
                            {
                                name: '신민호',
                                photo: '신민호',
                                roles: ['솔루션파트/Sr.Manager'],
                                email: 'rossshin@igisam.com',
                                phone: '010-6593-2239',
                            },
                        ]
                    },
                    {
                        groupTitle: '펀드운용',
                        members: [
                            {
                                name: '김행단',
                                photo: '김행단',
                                roles: ['국내자산관리그룹/그룹장', '자산관리2파트/그룹장', '전략펀드운용1실', 'IOTA CFT'],
                                responsibility: '펀드운용 책임인력',
                                email: 'hkim@igisam.com',
                                phone: '010-2995-2352',
                            },
                        ]
                    },
                    {
                        groupTitle: 'IPR',
                        members: [
                            {
                                name: '윤용택',
                                photo: '윤용택',
                                roles: ['사업그룹3파트/Sr.Manager', '전략펀드운용1실', '개발PFV TF'],
                                responsibility: 'IPR 책임인력',
                                email: 'yongtek.yoon@igisam.com',
                                phone: '010-2655-1185',
                            },
                        ]
                    },
]